# Generated by Django 2.2.4 on 2020-06-01 06:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('delDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lastName', models.CharField(max_length=120, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('desc', models.TextField(max_length=500, verbose_name='Description')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagra,')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('delDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category name')),
                ('imageRef', models.ImageField(upload_to='category/', verbose_name='Reference image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('delDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('lastName', models.CharField(max_length=150, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('topic', models.CharField(max_length=100, verbose_name='Topic')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('delDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('delDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Suscription',
                'verbose_name_plural': 'Suscriptions',
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('delDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('aboutUs', models.TextField(verbose_name='About us')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('delDate', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug')),
                ('desc', models.TextField(verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField()),
                ('refImage', models.ImageField(max_length=255, upload_to='images/', verbose_name='Ref image')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('publishDate', models.DateField(verbose_name='Publish date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
