# Generated by Django 2.2.4 on 2020-06-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='refImage',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='authors/', verbose_name='Ref image'),
        ),
    ]
